### ISSUE TITLE
How to use this hook in complex codebases

### ISSUE THREAD

**Issue by mertcihankurel** [sparksuite/react-accessible-dropdown-menu-hook#288]
I love this hook thanks for your all efforts here. I want to implement it in our complex codebase(react + typescript) but docs are not clear descriptive for me. İs there any tutorial to show me how to use it like I'm five?

**Comment by corymharper** [comment]
Hi @mcihadkurel ,

Thanks for the interest in our package, I'm glad you like it!

There isn't directly a tutorial for the usage of the hook. However, the basic usage documentation is more or less supposed to serve that purpose.Have you taken a look at it?  If not, I encourage you to do so: https://sparksuite.github.io/react-accessible-dropdown-menu-hook/docs/getting-started/using

From there, if you need more detailed information about exactly what the hook returns when called, see the "Return object" documentation:

https://sparksuite.github.io/react-accessible-dropdown-menu-hook/docs/design/return-object

That provides a very details breakdown of what the whole return object contains with descriptions for each value.

Lastly, if you have or after you have reviewed that documentation, if you have specific questions about applications in certain use cases or if you have specific pain points we can address, let me know in a reply!

**Comment by mertcihankurel** [comment]
Hi Cory, 

Thank you for your clarification. One thing that makes me confusing is, in the example you show in demo is a button. But we are using div as a dropdown menu to expand and collapse items. How can I spread this buttonProps to a div?

**Comment by corymharper** [comment]
My initial suggestion is, if possible, just use buttons instead of divs. Buttons are inherently interactive where divs are not. However, to fully answer your question, full functionality for non-button menubuttons is not currently implemented in our package. You can see https://github.com/sparksuite/react-accessible-dropdown-menu-hook/issues/69 for more information. 

No one has opened a pull request to resolve that issue yet, and we always welcome new contributors to the repo!
