### ISSUE TITLE
Difference to downshift?

### ISSUE THREAD

**Issue by filipjnc** [sparksuite/react-accessible-dropdown-menu-hook#301]
I've been using the relatively popular library `downshift` for this use-case. 
https://github.com/downshift-js/downshift

What are the differentiating factors? Thanks!

**Comment by WesCossick** [comment]
While we don't have experience using Downshift here at Sparksuite, from a cursory review of that project's information, it appears to be larger in scope and therefore it's a much larger package with greater complexity. A quick comparison of the size:

&nbsp; | Downshift | RADMH
--- | --- | ---
Unpacked size | 2.51 MB | 0.0134 MB
Dependencies in tree | 10 | 0

There's also a substantial difference in the size of the READMEs, the documentation you'd need to read through, and the amount of boilerplate code you'd need to write to get up-and-running, with RADMH being significantly more minimal in all cases.

Our package is also published and maintained by an established company (@sparksuite) rather than an individual, which can influence how some people choose packages.

If all you're doing is building a dropdown menu, and you want it to be accessible, then it seems like our package would accomplish that very efficiently. If you need the other functionality offered by Downshift, then that package may be a better fit.
