### ISSUE TITLE
Can't use moveFocus to focus on the currently selected option

### ISSUE THREAD

**Issue by RoelN** [sparksuite/react-accessible-dropdown-menu-hook#302]
I have a dropdown with four options. If the user has selected option 3, I would like this to be focused when the dropdown has been opened:

Unopened state:

```
[ Option 3 ]
```

Opened state:

```
[ Option 3 ]
------------
[*Option 1*] // Is focussed
[ Option 2 ]
[ Option 3 ]
[ Option 4 ]
```

Desired result:

```
[ Option 3 ]
------------
[ Option 1 ]
[ Option 2 ]
[*Option 3*] // Is focussed
[ Option 4 ]
```

I've tried `moveFocus(2)` in the opening button's onClick, but this seems to do nothing.

Note that I am using buttons instead of anchors (as demonstrated [here](https://github.com/sparksuite/react-accessible-dropdown-menu-hook/issues/295)), but using anchors doesn't seem to make a difference. What am I doing wrong?

**Comment by corymharper** [comment]
You probably aren't doing anything wrong. Off the top of my head this is most likely a race condition. There are effects registered in the hook that move the focus to the first item when you open the menu (see https://github.com/sparksuite/react-accessible-dropdown-menu-hook/blob/master/src/use-dropdown-menu.ts#L67), mostly because thats what the specification says to do. 

However, there is an option you can pass to the hook to disable that behavior entirely. See the documentation on the `disableFocusFirstItemOnClick` option here: https://sparksuite.github.io/react-accessible-dropdown-menu-hook/docs/design/options. That would probably help solve your problem. You might run into the issue of the item you're trying to focus not being visible when you try to focus it, you could theoretically replicate what we've done in the effect I linked above, but to focus on the item you desire to sidestep that.

I hope that helps!

**Comment by RoelN** [comment]
Sorry, I should've mentioned I've tried with either `disableFocusFirstItemOnClick: true`.

But I realised I was doing the `moveFocus` in the main button's `onClick` event instead of inside a `useEffect`. The following code works, regardless of the value set for `disableFocusFirstItemOnClick`!

```javascript
useEffect(() => {
    if (isOpen) {
        moveFocus(currentIndex)
    }
}, [isOpen, moveFocus, currentIndex])
```

(Where `currentIndex` obviously points to the current index :-))

Thanks for taking the time to answer, and again for the great dropdown!

**Comment by corymharper** [comment]
I'd still use `disableFocusFirstItemOnClick: true` in your case even if it works in both cases, whats probably happening when the option isn't passed is a very fast focus on first item -> focus on the item you desire, which from some users perspectives could be very confusing. Thanks for using our package!
